### PR TITLE
Add support for SVN repositories and source archives

### PR DESCRIPTION
**Pull request by pmderodat**

### CODE REVIEW

**Comment by mosteo** [comment]
Is it possible that this commit depends on unmerged changes in alire? Even after merging Alire PR#33 there is no commit 645fbb44c6ac76dc2eb31da063965696784d183d in alire

**Comment by pmderodat** [comment]
You’re right, and that’s probably because I amended my commits in Alire. I’ll clean this up first thing next morning!

**Comment by pmderodat** [comment]
Done :-)

**Comment by mosteo** [comment]
I'm now getting this error:

`alr-origins.adb:9:06: file "alr-origins-source_archive.ads" not found`

Very puzzling because CI didn't fail.

**Comment by pmderodat** [comment]
I think I did something wrong while editing my commits… sorry about that! I’m about to resubmit a pull request to add the missing files.

**Pull request merged**
